server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

oauth:
  base-url: http://localhost:8081
  client-id: Ov23liZStKKHIXGdwKA4
  client-secret: e1372032e2e78c792864958188b24c4c40a193b5