name: cd

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: prod

    steps:
      - name: create docker-compose
        run: |
          cd ~/deploy-pic 
          sudo chmod +x create-compose-with-setup.sh
          ./create-compose-with-setup.sh

      - name: docker-compose run
        run: |
          docker compose -f ~/deploy-pic/docker-compose-springboot.yml down
          docker compose -f ~/deploy-pic/docker-compose-springboot.yml pull
          docker compose -f ~/deploy-pic/docker-compose-springboot.yml up -d

      - name: prune docker images
        run: |
          docker image prune -a -f
          
      

          
