name: cd

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: prod

    steps:
      - name: run deploy
        run: |
          cd ~/deploy-pic 
          sudo chmod +x deploy.sh
          ./deploy.sh springboot
